server:
  port: 8761

spring:
  application:
    name: eureka-server

# 单机注册中心：不向自己注册、也不拉取注册表（只做「服务端」）
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
